import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import type { OuroForgeManifest } from './manifest';
import {
    GENERATED_THEME_FILE,
    GENERATED_TOKENS_FILE,
    GENERATED_COMPONENTS_FILE,
    GENERATED_STYLES_FILE,
    generateRustFiles,
} from './rustGenerator';
import { run } from '../../tools/ouroforge-rust';

const manifest: OuroForgeManifest = {
    schemaVersion: 2,
    kind: 'ouroforge.tokens',
    adapterId: 'ouroboros',
    source: { revision: 'c390d7d' },
    collection: { name: 'Ouroboros', modes: ['Light', 'Dark'] },
    tokens: [
        { path: 'primitive/zinc/50', type: 'color', values: { Light: '#fafafa', Dark: '#fafafa' } },
        { path: 'primitive/zinc/950', type: 'color', values: { Light: '#09090b', Dark: '#09090b' } },
        { path: 'background', type: 'color', values: { Light: { alias: 'primitive/zinc/50' }, Dark: { alias: 'primitive/zinc/950' } } },
        { path: 'surface', type: 'color', values: { Light: { alias: 'background' }, Dark: { alias: 'background' } } },
        { path: 'opacity/disabled', type: 'number', unit: 'opacity', values: { Light: 0.5, Dark: 0.5 } },
        {
            path: 'motion/duration/fast',
            type: 'duration',
            unit: 'ms',
            values: { Light: 100, Dark: 100 },
            codeSyntax: { RUST: 'ouroboros_ui::tokens::core::DURATION_FAST' },
        },
    ],
    styles: {
        text: [{
            name: 'ouroboros/body', fontFamily: 'Iosevka Light', fontStyle: 'Regular', fontSize: 14,
            bindings: { fontSize: 'spacing/4' },
        }],
        effects: [{ name: 'shadow/sm', effects: [] }],
    },
    components: [{
        id: 'button',
        name: 'Ouroboros/atoms/Button',
        rustPath: 'ouroboros_ui::atoms::Button',
        fidelity: 'visual-facsimile',
        variants: [
            {
                key: 'Variant=Default', name: 'Variant=Default', layout: 'HORIZONTAL',
                width: 180, height: 32, itemSpacing: 8,
                padding: { top: 8, right: 12, bottom: 8, left: 12 },
            },
            {
                key: 'Variant=Secondary', name: 'Variant=Secondary', layout: 'HORIZONTAL',
                width: 164, height: 30, itemSpacing: 6,
                padding: { top: 6, right: 10, bottom: 6, left: 10 },
            },
        ],
    }],
};

describe('Rust write-back generator', () => {
    it('generates stable owned modules and resolves aliases in the matching mode', () => {
        const first = generateRustFiles(manifest);
        const second = generateRustFiles(structuredClone(manifest));
        expect(first).toEqual(second);
        expect(first[GENERATED_TOKENS_FILE]).toMatchInlineSnapshot(`
          "// @generated by OuroForge. DO NOT EDIT.
          // Source revision: c390d7d

          use egui::Color32;

          pub const OUROFORGE_SOURCE_REVISION: &str = \"c390d7d\";

          pub const DURATION_FAST: f32 = 0.1;
          pub const OPACITY_DISABLED: f32 = 0.5;
          pub const PRIMITIVE_ZINC_50: Color32 = Color32::from_rgb(250, 250, 250);
          pub const PRIMITIVE_ZINC_950: Color32 = Color32::from_rgb(9, 9, 11);
          "
        `);
        expect(first[GENERATED_THEME_FILE]).toContain('background: PRIMITIVE_ZINC_50,');
        expect(first[GENERATED_THEME_FILE]).toContain('background: PRIMITIVE_ZINC_950,');
        expect(first[GENERATED_THEME_FILE]).toContain('surface: PRIMITIVE_ZINC_50,');
        expect(first[GENERATED_THEME_FILE]).toContain('surface: PRIMITIVE_ZINC_950,');
        expect(first[GENERATED_COMPONENTS_FILE]).toContain('rust_path: "ouroboros_ui::atoms::Button"');
        expect(first[GENERATED_COMPONENTS_FILE]).toContain('key: "Variant=Default"');
        expect(first[GENERATED_COMPONENTS_FILE]).toContain('width: 180.0');
        expect(first[GENERATED_COMPONENTS_FILE]).toContain('key: "Variant=Secondary"');
        expect(first[GENERATED_COMPONENTS_FILE]).toContain('width: 164.0');
        expect(first[GENERATED_STYLES_FILE]).toContain('OuroForgeTextStyleRecipe');
        expect(first[GENERATED_STYLES_FILE]).toContain('font_family: "Iosevka Light"');
        expect(first[GENERATED_STYLES_FILE]).toContain('bindings_json: "{\\"fontSize\\":\\"spacing/4\\"}"');
        expect(first[GENERATED_STYLES_FILE]).toContain('OuroForgeEffectStyleRecipe');
    });

    it('writes only owned generated filenames and supports drift checks', async () => {
        const root = await mkdtemp(join(tmpdir(), 'ouroforge-'));
        const manifestPath = join(root, 'manifest.json');
        const output = join(root, 'generated');
        const handwritten = join(root, 'theme.rs');
        await writeFile(manifestPath, JSON.stringify(manifest), 'utf8');
        await writeFile(handwritten, '// handwritten\n', 'utf8');
        expect(await run(['--manifest', manifestPath, '--out-dir', output])).toBe(0);
        expect(await run(['--manifest', manifestPath, '--out-dir', output, '--check'])).toBe(0);
        expect(await run(['--manifest', manifestPath, '--out-dir', output])).toBe(0);
        expect(await readFile(handwritten, 'utf8')).toBe('// handwritten\n');
        expect(await readFile(join(output, GENERATED_TOKENS_FILE), 'utf8')).toContain('@generated by OuroForge');
        expect(await readFile(join(output, GENERATED_COMPONENTS_FILE), 'utf8')).toContain('OUROFORGE_COMPONENTS');
        expect(await readFile(join(output, GENERATED_STYLES_FILE), 'utf8')).toContain('OUROFORGE_TEXT_STYLES');
    });

    it('rejects unknown aliases instead of generating invalid Rust', () => {
        const bad = structuredClone(manifest);
        bad.tokens[2].values.Dark = { alias: 'missing' };
        expect(() => generateRustFiles(bad)).toThrow(/unknown alias/);
    });
});
