import type { ManifestToken, ManifestValue, OuroForgeManifest } from './manifest';
import { validateOuroForgeManifest } from './manifest';

export const GENERATED_TOKENS_FILE = 'ouroforge_tokens.generated.rs';
export const GENERATED_THEME_FILE = 'ouroforge_theme.generated.rs';
export const GENERATED_COMPONENTS_FILE = 'ouroforge_components.generated.rs';
export const GENERATED_STYLES_FILE = 'ouroforge_styles.generated.rs';

export interface GeneratedRustFiles {
    [GENERATED_TOKENS_FILE]: string;
    [GENERATED_THEME_FILE]: string;
    [GENERATED_COMPONENTS_FILE]: string;
    [GENERATED_STYLES_FILE]: string;
}

function rustIdentifier(path: string): string {
    const value = path
        .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
        .replace(/[^A-Za-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '')
        .toUpperCase();
    return /^[0-9]/.test(value) ? `TOKEN_${value}` : value;
}

function rustIdentifierFor(token: ManifestToken): string {
    const syntax = token.codeSyntax?.RUST;
    const explicit = syntax?.match(/::([A-Z][A-Z0-9_]*)$/)?.[1];
    return explicit || rustIdentifier(token.path);
}

function rustField(path: string): string {
    const value = path
        .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
        .replace(/[^A-Za-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '')
        .toLowerCase();
    return /^[0-9]/.test(value) ? `token_${value}` : value;
}

function escaped(value: string): string {
    return JSON.stringify(value);
}

function rustType(token: ManifestToken): string {
    if (token.type === 'boolean') return 'bool';
    if (token.type === 'color') return 'Color32';
    if (token.type === 'string') return "&'static str";
    return 'f32';
}

function colorLiteral(token: ManifestToken, value: string): string {
    const match = value.match(/^#([0-9a-fA-F]{6})([0-9a-fA-F]{2})?$/);
    if (!match) throw new Error(`Token "${token.path}" has unsupported Rust color "${value}".`);
    const channels = [0, 2, 4].map((offset) => Number.parseInt(match[1].slice(offset, offset + 2), 16));
    if (match[2]) {
        channels.push(Number.parseInt(match[2], 16));
        return `Color32::from_rgba_unmultiplied(${channels.join(', ')})`;
    }
    return `Color32::from_rgb(${channels.join(', ')})`;
}

function literal(
    token: ManifestToken,
    value: ManifestValue,
    mode: string,
    tokens: Map<string, ManifestToken>,
    symbols: Map<string, string>,
    seen: Set<string> = new Set(),
): string {
    if (value && typeof value === 'object') {
        const targetToken = tokens.get(value.alias);
        if (!targetToken) throw new Error(`Token "${token.path}" references unknown alias "${value.alias}".`);
        if (rustType(targetToken) !== rustType(token)) {
            throw new Error(`Token "${token.path}" aliases incompatible token "${value.alias}".`);
        }
        if (seen.has(value.alias)) throw new Error(`Alias cycle detected at "${value.alias}".`);
        const constant = symbols.get(value.alias);
        if (constant) return constant;
        return literal(targetToken, targetToken.values[mode], mode, tokens, symbols, new Set([...seen, value.alias]));
    }
    if (value === null) throw new Error(`Token "${token.path}" cannot generate Rust from null.`);
    if (typeof value === 'string') return token.type === 'color' ? colorLiteral(token, value) : escaped(value);
    if (typeof value === 'boolean') return String(value);
    if (!Number.isFinite(value)) throw new Error(`Token "${token.path}" has a non-finite numeric value.`);
    // Ouroboros/egui duration constants are f32 seconds; Figma/DTCG duration
    // values commonly use milliseconds. The manifest unit makes this exact.
    const rustValue = token.type === 'duration' && token.unit === 'ms' ? value / 1000 : value;
    return Number.isInteger(rustValue) ? `${rustValue}.0` : String(rustValue);
}

function header(manifest: OuroForgeManifest): string[] {
    return [
        '// @generated by OuroForge. DO NOT EDIT.',
        `// Source revision: ${manifest.source.revision}`,
        '',
    ];
}

function resolvedValue(
    token: ManifestToken,
    mode: string,
    tokens: Map<string, ManifestToken>,
    seen: Set<string> = new Set(),
): ManifestValue {
    const value = token.values[mode];
    if (!value || typeof value !== 'object') return value;
    const target = tokens.get(value.alias);
    if (!target) throw new Error(`Token "${token.path}" references unknown alias "${value.alias}".`);
    if (seen.has(value.alias)) throw new Error(`Alias cycle detected at "${value.alias}".`);
    return resolvedValue(target, mode, tokens, new Set([...seen, value.alias]));
}

/** Pure deterministic generator. It never reads or mutates an Ouroboros checkout. */
export function generateRustFiles(input: unknown): GeneratedRustFiles {
    const validation = validateOuroForgeManifest(input);
    if (!validation.ok || !validation.manifest) {
        throw new Error(`Invalid OuroForge manifest:\n${validation.errors.join('\n')}`);
    }
    const manifest = validation.manifest;
    const sorted = [...manifest.tokens].sort((left, right) => left.path.localeCompare(right.path));
    const firstMode = manifest.collection.modes[0];
    const tokenMap = new Map(sorted.map((token) => [token.path, token]));
    const constants = sorted.filter((token) => manifest.collection.modes.every((mode) =>
        JSON.stringify(resolvedValue(token, mode, tokenMap, new Set([token.path])))
            === JSON.stringify(resolvedValue(token, firstMode, tokenMap, new Set([token.path]))),
    ));
    const themed = sorted.filter((token) => !constants.includes(token));
    const symbols = new Map(constants.map((token) => [token.path, rustIdentifierFor(token)]));
    const duplicateSymbols = [...symbols.values()].filter((symbol, index, all) => all.indexOf(symbol) !== index);
    if (duplicateSymbols.length) throw new Error(`Duplicate generated Rust symbol: ${duplicateSymbols[0]}.`);

    const tokenLines = header(manifest);
    if (constants.some((token) => token.type === 'color')) tokenLines.push('use egui::Color32;', '');
    tokenLines.push(`pub const OUROFORGE_SOURCE_REVISION: &str = ${escaped(manifest.source.revision)};`, '');
    for (const token of constants) {
        tokenLines.push(`pub const ${symbols.get(token.path)}: ${rustType(token)} = ${literal(token, token.values[firstMode], firstMode, tokenMap, symbols)};`);
    }

    const themeLines = header(manifest);
    themeLines.push('use super::ouroforge_tokens::*;');
    if (themed.some((token) => token.type === 'color')) themeLines.push('use egui::Color32;');
    themeLines.push('', '#[derive(Clone, Debug, PartialEq)]', 'pub struct OuroForgeTheme {');
    for (const token of themed) themeLines.push(`    pub ${rustField(token.path)}: ${rustType(token)},`);
    themeLines.push('}', '');
    for (const mode of manifest.collection.modes) {
        const constructor = rustField(mode);
        themeLines.push(`pub fn ${constructor}() -> OuroForgeTheme {`, '    OuroForgeTheme {');
        for (const token of themed) {
            themeLines.push(`        ${rustField(token.path)}: ${literal(token, token.values[mode], mode, tokenMap, symbols)},`);
        }
        themeLines.push('    }', '}', '');
    }

    const componentLines = header(manifest);
    componentLines.push(
        '#[derive(Clone, Copy, Debug, PartialEq)]',
        'pub struct OuroForgeComponentVariantRecipe {',
        "    pub key: &'static str,",
        "    pub name: &'static str,",
        "    pub layout: &'static str,",
        '    pub width: f32,',
        '    pub height: f32,',
        '    pub item_spacing: f32,',
        '    pub padding: [f32; 4],',
        '}',
        '',
        '#[derive(Clone, Copy, Debug, PartialEq)]',
        'pub struct OuroForgeComponentRecipe {',
        "    pub id: &'static str,",
        "    pub rust_path: &'static str,",
        "    pub fidelity: &'static str,",
        "    pub variants: &'static [OuroForgeComponentVariantRecipe],",
        '}',
        '',
        'pub const OUROFORGE_COMPONENTS: &[OuroForgeComponentRecipe] = &[',
    );
    for (const component of manifest.components || []) {
        componentLines.push(
            '    OuroForgeComponentRecipe {',
            `        id: ${escaped(component.id)},`,
            `        rust_path: ${escaped(component.rustPath)},`,
            `        fidelity: ${escaped(component.fidelity)},`,
            '        variants: &[',
        );
        for (const variant of component.variants) {
            componentLines.push(
                '            OuroForgeComponentVariantRecipe {',
                `                key: ${escaped(variant.key)},`,
                `                name: ${escaped(variant.name)},`,
                `                layout: ${escaped(variant.layout)},`,
                `                width: ${Number.isInteger(variant.width) ? `${variant.width}.0` : variant.width},`,
                `                height: ${Number.isInteger(variant.height) ? `${variant.height}.0` : variant.height},`,
                `                item_spacing: ${Number.isInteger(variant.itemSpacing) ? `${variant.itemSpacing}.0` : variant.itemSpacing},`,
                `                padding: [${[variant.padding.top, variant.padding.right, variant.padding.bottom, variant.padding.left]
                    .map(value => Number.isInteger(value) ? `${value}.0` : String(value)).join(', ')}],`,
                '            },',
            );
        }
        componentLines.push('        ],', '    },');
    }
    componentLines.push('];', '');

    const styleLines = header(manifest);
    styleLines.push(
        '#[derive(Clone, Copy, Debug, PartialEq)]',
        'pub struct OuroForgeTextStyleRecipe {',
        "    pub name: &'static str,",
        "    pub font_family: &'static str,",
        "    pub font_style: &'static str,",
        '    pub font_size: f32,',
        '    pub line_height: Option<f32>,',
        '    pub letter_spacing: Option<f32>,',
        "    pub bindings_json: &'static str,",
        '}',
        '',
        'pub const OUROFORGE_TEXT_STYLES: &[OuroForgeTextStyleRecipe] = &[',
    );
    for (const style of manifest.styles?.text || []) {
        const number = (value: number) => Number.isInteger(value) ? `${value}.0` : String(value);
        styleLines.push(
            '    OuroForgeTextStyleRecipe {',
            `        name: ${escaped(style.name)},`,
            `        font_family: ${escaped(style.fontFamily)},`,
            `        font_style: ${escaped(style.fontStyle)},`,
            `        font_size: ${number(style.fontSize)},`,
            `        line_height: ${style.lineHeight === undefined ? 'None' : `Some(${number(style.lineHeight)})`},`,
            `        letter_spacing: ${style.letterSpacing === undefined ? 'None' : `Some(${number(style.letterSpacing)})`},`,
            `        bindings_json: ${escaped(JSON.stringify(style.bindings || {}))},`,
            '    },',
        );
    }
    styleLines.push(
        '];',
        '',
        '#[derive(Clone, Copy, Debug, PartialEq)]',
        'pub struct OuroForgeEffectStyleRecipe {',
        "    pub name: &'static str,",
        "    pub effects_json: &'static str,",
        '}',
        '',
        'pub const OUROFORGE_EFFECT_STYLES: &[OuroForgeEffectStyleRecipe] = &[',
    );
    for (const style of manifest.styles?.effects || []) {
        styleLines.push(
            '    OuroForgeEffectStyleRecipe {',
            `        name: ${escaped(style.name)},`,
            `        effects_json: ${escaped(JSON.stringify(style.effects))},`,
            '    },',
        );
    }
    styleLines.push('];', '');

    return {
        [GENERATED_TOKENS_FILE]: tokenLines.join('\n') + '\n',
        [GENERATED_THEME_FILE]: themeLines.join('\n') + '\n',
        [GENERATED_COMPONENTS_FILE]: componentLines.join('\n') + '\n',
        [GENERATED_STYLES_FILE]: styleLines.join('\n') + '\n',
    };
}
