// ─── Ouroboros UI Adapter ───────────────────────────────────────────────────
// Mirrors the public core and semantic tokens from Ouroboros UI. The stable
// names here form the round-trip contract: Figma may edit values, while code
// generation can target the matching Rust token or Theme field.

import type { LibraryAdapter, ThemeExtras, ThemeResult, TokenCategory } from './types';

export const OUROBOROS_COMMIT = 'c390d7deffa7955e28b2e3bcb9c22ac0899a261b';

const primitiveColors: Record<string, string> = {
    'primitive/zinc/50': '#fafafa',
    'primitive/zinc/100': '#f4f4f5',
    'primitive/zinc/200': '#e4e4e7',
    'primitive/zinc/300': '#d4d4d8',
    'primitive/zinc/400': '#a1a1aa',
    'primitive/zinc/500': '#71717a',
    'primitive/zinc/600': '#52525b',
    'primitive/zinc/700': '#3f3f46',
    'primitive/zinc/800': '#27272a',
    'primitive/zinc/900': '#18181b',
    'primitive/zinc/950': '#09090b',
    'primitive/teal/200': '#99f6e4',
    'primitive/teal/300': '#5eead4',
    'primitive/teal/400': '#2dd4bf',
    'primitive/teal/500': '#14b8a6',
    'primitive/teal/600': '#0d9488',
    'primitive/green/500': '#22c55e',
    'primitive/red/500': '#ef4444',
    'primitive/amber/500': '#f59e0b',
    'primitive/blue/400': '#60a5fa',
    'primitive/blue/500': '#3b82f6',
    'primitive/scrim': 'rgba(0, 0, 0, 0.6)',
};

const aliases: NonNullable<ThemeExtras['aliases']> = [
    ['background', 'primitive/zinc/50', 'primitive/zinc/950'],
    ['foreground', 'primitive/zinc/950', 'primitive/zinc/50'],
    ['card', 'primitive/zinc/50', 'primitive/zinc/900'],
    ['card-foreground', 'primitive/zinc/950', 'primitive/zinc/50'],
    ['popover', 'primitive/zinc/50', 'primitive/zinc/900'],
    ['popover-foreground', 'primitive/zinc/950', 'primitive/zinc/50'],
    ['muted', 'primitive/zinc/100', 'primitive/zinc/800'],
    ['muted-foreground', 'primitive/zinc/500', 'primitive/zinc/400'],
    ['disabled-foreground', 'primitive/zinc/400', 'primitive/zinc/600'],
    ['primary', 'primitive/teal/400', 'primitive/teal/200'],
    ['primary-foreground', 'primitive/zinc/950', 'primitive/zinc/950'],
    ['primary-hover', 'primitive/teal/500', 'primitive/teal/300'],
    ['secondary', 'primitive/zinc/100', 'primitive/zinc/800'],
    ['secondary-foreground', 'primitive/zinc/900', 'primitive/zinc/50'],
    ['accent', 'primitive/zinc/100', 'primitive/zinc/800'],
    ['accent-foreground', 'primitive/zinc/900', 'primitive/zinc/50'],
    ['destructive', 'primitive/red/500', 'primitive/red/500'],
    ['destructive-foreground', 'primitive/zinc/50', 'primitive/zinc/50'],
    ['border', 'primitive/zinc/200', 'primitive/zinc/800'],
    ['border-strong', 'primitive/zinc/300', 'primitive/zinc/700'],
    ['input', 'primitive/zinc/200', 'primitive/zinc/800'],
    ['ring', 'primitive/teal/400', 'primitive/teal/300'],
    ['scrim', 'primitive/scrim', 'primitive/scrim'],
    ['success', 'primitive/green/500', 'primitive/green/500'],
    ['warning', 'primitive/amber/500', 'primitive/amber/500'],
    ['error', 'primitive/red/500', 'primitive/red/500'],
    ['info', 'primitive/blue/400', 'primitive/blue/400'],
    ['neutral', 'primitive/zinc/500', 'primitive/zinc/500'],
    ['theme/zinc/primary', 'primitive/zinc/900', 'primitive/zinc/50'],
    ['theme/zinc/primary-foreground', 'primitive/zinc/50', 'primitive/zinc/900'],
    ['theme/zinc/primary-hover', 'primitive/zinc/700', 'primitive/zinc/200'],
    ['theme/zinc/ring', 'primitive/zinc/400', 'primitive/zinc/300'],
].map(([name, lightTarget, darkTarget]) => ({
    name,
    lightTarget,
    darkTarget,
    scopes: ['ALL_FILLS', 'STROKE_COLOR', 'EFFECT_COLOR'],
    codeSyntax: `ouroboros_ui::tokens::semantic::Theme::${name.replace(/^theme\/zinc\//, '').replace(/-/g, '_')}`,
}));

const lightSemantic: Record<string, string> = {
    background: '#fafafa',
    foreground: '#09090b',
    card: '#fafafa',
    'card-foreground': '#09090b',
    popover: '#fafafa',
    'popover-foreground': '#09090b',
    muted: '#f4f4f5',
    'muted-foreground': '#71717a',
    'disabled-foreground': '#a1a1aa',
    primary: '#2dd4bf',
    'primary-foreground': '#09090b',
    'primary-hover': '#14b8a6',
    secondary: '#f4f4f5',
    'secondary-foreground': '#18181b',
    accent: '#f4f4f5',
    'accent-foreground': '#18181b',
    destructive: '#ef4444',
    'destructive-foreground': '#fafafa',
    border: '#e4e4e7',
    'border-strong': '#d4d4d8',
    input: '#e4e4e7',
    ring: '#2dd4bf',
    'hover-overlay': 'rgba(0, 0, 0, 0.06)',
    'press-overlay': 'rgba(0, 0, 0, 0.12)',
    scrim: 'rgba(0, 0, 0, 0.6)',
    success: '#22c55e',
    'success-bg': 'rgba(34, 197, 94, 0.149)',
    warning: '#f59e0b',
    'warning-bg': 'rgba(245, 158, 11, 0.149)',
    error: '#ef4444',
    'error-bg': 'rgba(239, 68, 68, 0.149)',
    info: '#60a5fa',
    'info-bg': 'rgba(59, 130, 246, 0.149)',
    neutral: '#71717a',
    'neutral-bg': 'rgba(113, 113, 122, 0.149)',
    'theme/zinc/primary': '#18181b',
    'theme/zinc/primary-foreground': '#fafafa',
    'theme/zinc/primary-hover': '#3f3f46',
    'theme/zinc/ring': '#a1a1aa',
};

const darkSemantic: Record<string, string> = {
    background: '#09090b',
    foreground: '#fafafa',
    card: '#18181b',
    'card-foreground': '#fafafa',
    popover: '#18181b',
    'popover-foreground': '#fafafa',
    muted: '#27272a',
    'muted-foreground': '#a1a1aa',
    'disabled-foreground': '#52525b',
    primary: '#99f6e4',
    'primary-foreground': '#09090b',
    'primary-hover': '#5eead4',
    secondary: '#27272a',
    'secondary-foreground': '#fafafa',
    accent: '#27272a',
    'accent-foreground': '#fafafa',
    destructive: '#ef4444',
    'destructive-foreground': '#fafafa',
    border: '#27272a',
    'border-strong': '#3f3f46',
    input: '#27272a',
    ring: '#5eead4',
    'hover-overlay': 'rgba(255, 255, 255, 0.06)',
    'press-overlay': 'rgba(255, 255, 255, 0.12)',
    scrim: 'rgba(0, 0, 0, 0.6)',
    success: '#22c55e',
    'success-bg': 'rgba(34, 197, 94, 0.149)',
    warning: '#f59e0b',
    'warning-bg': 'rgba(245, 158, 11, 0.149)',
    error: '#ef4444',
    'error-bg': 'rgba(239, 68, 68, 0.149)',
    info: '#60a5fa',
    'info-bg': 'rgba(59, 130, 246, 0.149)',
    neutral: '#71717a',
    'neutral-bg': 'rgba(113, 113, 122, 0.149)',
    'theme/zinc/primary': '#fafafa',
    'theme/zinc/primary-foreground': '#18181b',
    'theme/zinc/primary-hover': '#e4e4e7',
    'theme/zinc/ring': '#d4d4d8',
};

const rustFloat = (name: string, value: number, scopes: string[], rustPath: string) => ({
    name,
    value,
    scopes,
    codeSyntax: `ouroboros_ui::${rustPath}`,
});

const float = (name: string, value: number, scopes: string[], rustName: string) =>
    rustFloat(name, value, scopes, `tokens::core::${rustName}`);

const layoutFloat = (name: string, value: number, scopes: string[], rustName: string) =>
    rustFloat(name, value, scopes, `tokens::layout::${rustName}`);

const floats: NonNullable<ThemeExtras['floats']> = [
    ...[
        ['0', 0, 'SPACE_0'], ['1', 4, 'SPACE_1'], ['2', 8, 'SPACE_2'],
        ['3', 12, 'SPACE_3'], ['4', 16, 'SPACE_4'], ['5', 20, 'SPACE_5'],
        ['6', 24, 'SPACE_6'], ['8', 32, 'SPACE_8'], ['10', 40, 'SPACE_10'],
        ['12', 48, 'SPACE_12'],
    ].map(([name, value, rust]) => float(`spacing/${name}`, value as number, ['GAP'], rust as string)),
    ...[
        ['none', 0, 'RADIUS_NONE'], ['sm', 4, 'RADIUS_SM'], ['md', 6, 'RADIUS_MD'],
        ['lg', 8, 'RADIUS_LG'], ['xl', 12, 'RADIUS_XL'], ['full', 9999, 'RADIUS_FULL'],
    ].map(([name, value, rust]) => float(`radius/${name}`, value as number, ['CORNER_RADIUS'], rust as string)),
    ...[
        ['xs', 12, 'TEXT_XS'], ['sm', 13, 'TEXT_SM'], ['base', 14, 'TEXT_BASE'],
        ['lg', 16, 'TEXT_LG'], ['xl', 20, 'TEXT_XL'], ['2xl', 24, 'TEXT_2XL'],
        ['3xl', 30, 'TEXT_3XL'],
    ].map(([name, value, rust]) => float(`typography/size/${name}`, value as number, ['FONT_SIZE'], rust as string)),
    ...[
        ['tight', -0.25, 'TRACKING_TIGHT'], ['normal', 0, 'TRACKING_NORMAL'],
        ['sm', 0.4, 'TRACKING_SM'], ['md', 0.6, 'TRACKING_MD'],
        ['lg', 0.8, 'TRACKING_LG'], ['wide', 1, 'TRACKING_WIDE'],
    ].map(([name, value, rust]) => float(`typography/tracking/${name}`, value as number, ['LETTER_SPACING'], rust as string)),
    ...[
        ['tight', 1.2, 'LEADING_TIGHT'], ['normal', 1.45, 'LEADING_NORMAL'],
        ['relaxed', 1.6, 'LEADING_RELAXED'],
    ].map(([name, value, rust]) => float(`typography/leading/${name}`, value as number, [], rust as string)),
    ...[
        ['light', 300, 'Weight::Light'], ['regular', 400, 'Weight::Regular'],
        ['medium', 500, 'Weight::Medium'], ['semibold', 600, 'Weight::SemiBold'],
        ['bold', 700, 'Weight::Bold'],
    ].map(([name, value, rust]) => rustFloat(`typography/weight/${name}`, value as number, ['FONT_WEIGHT'], `theme::typography::${rust}`)),
    ...[
        ['display', 36], ['h1', 28.8], ['h2', 24], ['heading', 19.2],
        ['body', 20.3], ['body-strong', 20.3], ['label', 18.85],
        ['label-strong', 18.85], ['caption', 17.4], ['code', 18.85], ['kbd', 17.4],
    ].map(([name, value]) => rustFloat(
        `typography/role/${name}/line-height`,
        value as number,
        ['LINE_HEIGHT'],
        `theme::typography::${String(name).replace(/-/g, '_')}`
    )),
    ...[
        ['sm', 26, 'CONTROL_SM'], ['md', 32, 'CONTROL_MD'], ['lg', 38, 'CONTROL_LG'],
    ].map(([name, value, rust]) => float(`control/${name}`, value as number, ['WIDTH_HEIGHT'], rust as string)),
    ...[
        ['sm', 14, 'ICON_SM'], ['md', 16, 'ICON_MD'], ['lg', 20, 'ICON_LG'], ['xl', 24, 'ICON_XL'],
    ].map(([name, value, rust]) => float(`icon/${name}`, value as number, ['WIDTH_HEIGHT'], rust as string)),
    float('border/thin', 1, ['STROKE_FLOAT'], 'BORDER_THIN'),
    float('border/focus', 2, ['STROKE_FLOAT'], 'BORDER_FOCUS'),
    float('focus/ring-offset', 2, ['WIDTH_HEIGHT'], 'RING_OFFSET'),
    float('hit/minimum', 32, ['WIDTH_HEIGHT'], 'HIT_MIN'),
    float('opacity/disabled', 0.5, ['OPACITY'], 'OPACITY_DISABLED'),
    float('opacity/muted', 0.7, ['OPACITY'], 'OPACITY_MUTED'),
    float('opacity/hover-overlay', 0.06, ['OPACITY'], 'HOVER_OVERLAY'),
    float('opacity/press-overlay', 0.12, ['OPACITY'], 'PRESS_OVERLAY'),
    float('motion/duration/instant', 0, [], 'DURATION_INSTANT'),
    float('motion/duration/fast', 0.1, [], 'DURATION_FAST'),
    float('motion/duration/normal', 0.18, [], 'DURATION_NORMAL'),
    float('motion/duration/slow', 0.3, [], 'DURATION_SLOW'),
    float('motion/duration/delay-short', 0.15, [], 'DURATION_DELAY_SHORT'),
    float('motion/duration/delay-long', 0.5, [], 'DURATION_DELAY_LONG'),
    float('graph/grid-dot-radius', 1, ['WIDTH_HEIGHT'], 'GRID_DOT_RADIUS'),
    float('graph/grid-spacing', 28, ['GAP'], 'GRID_SPACING'),
    float('graph/edge-width', 2, ['STROKE_FLOAT'], 'EDGE_WIDTH'),
    float('graph/edge-hit-radius', 6, ['WIDTH_HEIGHT'], 'EDGE_HIT_RADIUS'),
    float('graph/handle-radius', 5, ['WIDTH_HEIGHT'], 'HANDLE_RADIUS'),
    float('graph/marquee-alpha', 38, [], 'MARQUEE_ALPHA'),
    layoutFloat('layout/sidebar-width', 240, ['WIDTH_HEIGHT'], 'SIDEBAR_WIDTH'),
    layoutFloat('layout/inspector-width', 300, ['WIDTH_HEIGHT'], 'INSPECTOR_WIDTH'),
    layoutFloat('layout/panel-min', 180, ['WIDTH_HEIGHT'], 'PANEL_MIN'),
    layoutFloat('layout/panel-max', 480, ['WIDTH_HEIGHT'], 'PANEL_MAX'),
    layoutFloat('layout/toolbar-height', 40, ['WIDTH_HEIGHT'], 'TOOLBAR_HEIGHT'),
    layoutFloat('layout/statusbar-height', 24, ['WIDTH_HEIGHT'], 'STATUSBAR_HEIGHT'),
    layoutFloat('layout/panel-pad', 16, ['GAP'], 'PANEL_PAD'),
    layoutFloat('layout/panel-gap', 8, ['GAP'], 'PANEL_GAP'),
    layoutFloat('layout/grid-columns', 12, [], 'GRID_COLUMNS'),
    layoutFloat('layout/grid-gutter', 16, ['GAP'], 'GRID_GUTTER'),
    layoutFloat('layout/container-max', 1200, ['WIDTH_HEIGHT'], 'CONTAINER_MAX'),
    layoutFloat('layout/breakpoint-compact', 720, ['WIDTH_HEIGHT'], 'BREAKPOINT_COMPACT'),
    layoutFloat('layout/breakpoint-normal', 1024, ['WIDTH_HEIGHT'], 'BREAKPOINT_NORMAL'),
    layoutFloat('layout/breakpoint-wide', 1440, ['WIDTH_HEIGHT'], 'BREAKPOINT_WIDE'),
    layoutFloat('layout/field-horizontal-min', 480, ['WIDTH_HEIGHT'], 'FIELD_HORIZONTAL_MIN'),
    layoutFloat('layout/property-label-width', 120, ['WIDTH_HEIGHT'], 'PROPERTY_LABEL_WIDTH'),
    layoutFloat('layout/inspector-row-stack-min', 220, ['WIDTH_HEIGHT'], 'INSPECTOR_ROW_STACK_MIN'),
    layoutFloat('layout/table-row-height', 28, ['WIDTH_HEIGHT'], 'TABLE_ROW_HEIGHT'),
    layoutFloat('layout/control-min-width', 72, ['WIDTH_HEIGHT'], 'CONTROL_MIN_W'),
    layoutFloat('layout/input-min-width', 96, ['WIDTH_HEIGHT'], 'INPUT_MIN_W'),
    layoutFloat('layout/numeric-min-width', 48, ['WIDTH_HEIGHT'], 'NUMERIC_MIN_W'),
    layoutFloat('layout/numeric-stepper-min-width', 88, ['WIDTH_HEIGHT'], 'NUMERIC_STEPPER_MIN_W'),
    layoutFloat('layout/field-number-width', 120, ['WIDTH_HEIGHT'], 'FIELD_NUM_W'),
    layoutFloat('layout/numeric-stepper-width', 120, ['WIDTH_HEIGHT'], 'NUMERIC_STEPPER_W'),
    layoutFloat('layout/slider-min-width', 120, ['WIDTH_HEIGHT'], 'SLIDER_MIN_W'),
    layoutFloat('layout/progress-min-width', 64, ['WIDTH_HEIGHT'], 'PROGRESS_MIN_W'),
];

const extras: ThemeExtras = {
    floats,
    aliases,
    strings: [
        { name: 'typography/font-sans', value: 'Iosevka', scopes: ['FONT_FAMILY'], codeSyntax: 'ouroboros_ui::theme::typography' },
        { name: 'typography/font-mono', value: 'Iosevka Term', scopes: ['FONT_FAMILY'], codeSyntax: 'ouroboros_ui::theme::typography' },
    ],
    shadows: [
        { name: 'shadow/sm', value: '0 1px 2px 0 rgba(0, 0, 0, 0.239)' },
        { name: 'shadow/md', value: '0 2px 4px 0 rgba(0, 0, 0, 0.322)' },
        { name: 'shadow/lg', value: '0 8px 24px 0 rgba(0, 0, 0, 0.188)' },
    ],
    textStyles: [
        { name: 'ouroboros/display', family: 'Iosevka', fontStyle: 'Bold', fontSize: 30, fontWeight: 700, lineHeight: 36, letterSpacing: 0, bindings: { fontSize: 'typography/size/3xl', lineHeight: 'typography/role/display/line-height', letterSpacing: 'typography/tracking/normal' } },
        { name: 'ouroboros/h1', family: 'Iosevka Semibold', fontStyle: 'Regular', fontSize: 24, fontWeight: 600, lineHeight: 28.8, letterSpacing: 0, bindings: { fontSize: 'typography/size/2xl', lineHeight: 'typography/role/h1/line-height', letterSpacing: 'typography/tracking/normal' } },
        { name: 'ouroboros/h2', family: 'Iosevka Semibold', fontStyle: 'Regular', fontSize: 20, fontWeight: 600, lineHeight: 24, letterSpacing: 0, bindings: { fontSize: 'typography/size/xl', lineHeight: 'typography/role/h2/line-height', letterSpacing: 'typography/tracking/normal' } },
        { name: 'ouroboros/heading', family: 'Iosevka Semibold', fontStyle: 'Regular', fontSize: 16, fontWeight: 600, lineHeight: 19.2, letterSpacing: 0.4, bindings: { fontSize: 'typography/size/lg', lineHeight: 'typography/role/heading/line-height', letterSpacing: 'typography/tracking/sm' } },
        { name: 'ouroboros/body', family: 'Iosevka Light', fontStyle: 'Regular', fontSize: 14, fontWeight: 300, lineHeight: 20.3, letterSpacing: 0.6, bindings: { fontSize: 'typography/size/base', lineHeight: 'typography/role/body/line-height', letterSpacing: 'typography/tracking/md' } },
        { name: 'ouroboros/body-strong', family: 'Iosevka Medium', fontStyle: 'Regular', fontSize: 14, fontWeight: 500, lineHeight: 20.3, letterSpacing: 0.6, bindings: { fontSize: 'typography/size/base', lineHeight: 'typography/role/body-strong/line-height', letterSpacing: 'typography/tracking/md' } },
        { name: 'ouroboros/label', family: 'Iosevka Light', fontStyle: 'Regular', fontSize: 13, fontWeight: 300, lineHeight: 18.85, letterSpacing: 0.8, bindings: { fontSize: 'typography/size/sm', lineHeight: 'typography/role/label/line-height', letterSpacing: 'typography/tracking/lg' } },
        { name: 'ouroboros/label-strong', family: 'Iosevka Medium', fontStyle: 'Regular', fontSize: 13, fontWeight: 500, lineHeight: 18.85, letterSpacing: 0.8, bindings: { fontSize: 'typography/size/sm', lineHeight: 'typography/role/label-strong/line-height', letterSpacing: 'typography/tracking/lg' } },
        { name: 'ouroboros/caption', family: 'Iosevka', fontStyle: 'Regular', fontSize: 12, fontWeight: 400, lineHeight: 17.4, letterSpacing: 1, bindings: { fontSize: 'typography/size/xs', lineHeight: 'typography/role/caption/line-height', letterSpacing: 'typography/tracking/wide' } },
        { name: 'ouroboros/code', family: 'Iosevka Term', fontStyle: 'Regular', fontSize: 13, fontWeight: 400, lineHeight: 18.85, letterSpacing: 0.8, bindings: { fontSize: 'typography/size/sm', lineHeight: 'typography/role/code/line-height', letterSpacing: 'typography/tracking/lg' } },
        { name: 'ouroboros/kbd', family: 'Iosevka Term', fontStyle: 'Bold', fontSize: 12, fontWeight: 700, lineHeight: 17.4, letterSpacing: 1, bindings: { fontSize: 'typography/size/xs', lineHeight: 'typography/role/kbd/line-height', letterSpacing: 'typography/tracking/wide' } },
    ],
};

export const ouroborosAdapter: LibraryAdapter = {
    id: 'ouroboros',
    name: 'Ouroboros UI',
    description: 'Rust/egui semantic theme, core scale, typography, shadows and control metrics.',
    icon: 'ouroboros',
    repoUrl: 'https://github.com/Type-zero-labs/ouroboros-ui',
    type: 'theme',
    dependencies: [],
    defaultCollectionName: 'Ouroboros',
    categories: [
        'colors', 'spacing', 'radius', 'shadows', 'typography', 'opacity',
        'borderWidth', 'breakpoints', 'containers', 'maxWidth',
        'motion', 'graph', 'layout', 'components',
    ] as TokenCategory[],

    async fetchAndParse(): Promise<ThemeResult> {
        return {
            type: 'theme',
            tokens: {
                light: { ...primitiveColors, ...lightSemantic },
                dark: { ...primitiveColors, ...darkSemantic },
            },
            source: {
                kind: 'bundled',
                version: OUROBOROS_COMMIT,
            },
            extras,
        };
    },
};
